[2024-10-04 09:03:05] [[31merror[39m] Error: 
    at Query.run (C:\My project\My project\back-end\node_modules\sequelize\src\dialects\mysql\query.js:46:25)
    at C:\My project\My project\back-end\node_modules\sequelize\src\sequelize.js:650:28
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at MySQLQueryInterface.select (C:\My project\My project\back-end\node_modules\sequelize\src\dialects\abstract\query-interface.js:1001:12)
    at Function.findAll (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1824:21)
    at async Promise.all (index 1)
    at Function.findAndCountAll (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:2183:27)
[2024-10-04 09:03:58] [[31merror[39m] Error: 
    at Query.run (C:\My project\My project\back-end\node_modules\sequelize\src\dialects\mysql\query.js:46:25)
    at C:\My project\My project\back-end\node_modules\sequelize\src\sequelize.js:650:28
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at MySQLQueryInterface.select (C:\My project\My project\back-end\node_modules\sequelize\src\dialects\abstract\query-interface.js:1001:12)
    at Function.findAll (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1824:21)
    at async Promise.all (index 1)
    at Function.findAndCountAll (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:2183:27)
[2024-10-04 09:04:52] [[31merror[39m] TypeError: Invalid attempt to destructure non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.
    at _nonIterableRest (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\nonIterableRest.js:2:9)
    at _slicedToArray (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\slicedToArray.js:6:97)
    at _callee2$ (C:\My project\My project\back-end\src\services\/kanjiService.js:55:11)
    at tryCatch (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:17)
    at _next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:17:9)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
[2024-10-04 09:05:09] [[31merror[39m] Error: Invalid value {}
    at Object.escape (C:\My project\My project\back-end\node_modules\sequelize\src\sql-string.js:66:11)
    at MySQLQueryGenerator.escape (C:\My project\My project\back-end\node_modules\sequelize\src\dialects\abstract\query-generator.js:1122:22)
    at MySQLQueryGenerator.addLimitAndOffset (C:\My project\My project\back-end\node_modules\sequelize\src\dialects\abstract\query-generator.js:2297:36)
    at MySQLQueryGenerator.selectQuery (C:\My project\My project\back-end\node_modules\sequelize\src\dialects\abstract\query-generator.js:1511:29)
    at MySQLQueryInterface.select (C:\My project\My project\back-end\node_modules\sequelize\src\dialects\abstract\query-interface.js:1002:27)
    at Function.findAll (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1824:47)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Promise.all (index 1)
    at Function.findAndCountAll (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:2183:27)
[2024-10-04 09:08:58] [[31merror[39m] TypeError: Invalid attempt to destructure non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.
    at _nonIterableRest (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\nonIterableRest.js:2:9)
    at _slicedToArray (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\slicedToArray.js:6:97)
    at _callee2$ (C:\My project\My project\back-end\src\services\/kanjiService.js:55:76)
    at tryCatch (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:17)
    at _next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:17:9)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
[2024-10-04 09:09:19] [[31merror[39m] TypeError: Invalid attempt to destructure non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.
    at _nonIterableRest (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\nonIterableRest.js:2:9)
    at _slicedToArray (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\slicedToArray.js:6:97)
    at _callee2$ (C:\My project\My project\back-end\src\services\/kanjiService.js:56:76)
    at tryCatch (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:17)
    at _next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:17:9)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
[2024-10-04 09:09:52] [[31merror[39m] TypeError: Invalid attempt to destructure non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.
    at _nonIterableRest (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\nonIterableRest.js:2:9)
    at _slicedToArray (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\slicedToArray.js:6:97)
    at _callee2$ (C:\My project\My project\back-end\src\services\/kanjiService.js:56:76)
    at tryCatch (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:17)
    at _next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:17:9)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
[2024-10-04 09:10:10] [[31merror[39m] TypeError: Invalid attempt to destructure non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.
    at _nonIterableRest (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\nonIterableRest.js:2:9)
    at _slicedToArray (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\slicedToArray.js:6:97)
    at _callee2$ (C:\My project\My project\back-end\src\services\/kanjiService.js:56:76)
    at tryCatch (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:17)
    at _next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:17:9)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
[2024-10-04 11:15:05] [[31merror[39m] TypeError: Cannot read properties of null (reading 'password')
    at _callee$ (C:\My project\My project\back-end\src\services\/authService.js:21:67)
    at tryCatch (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:17)
    at _next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:17:9)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
[2024-10-04 11:16:12] [[31merror[39m] TypeError: Cannot read properties of null (reading 'password')
    at _callee$ (C:\My project\My project\back-end\src\services\/authService.js:21:67)
    at tryCatch (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:17)
    at _next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:17:9)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
[2024-10-04 11:16:36] [[31merror[39m] TypeError: Cannot read properties of null (reading 'password')
    at _callee$ (C:\My project\My project\back-end\src\services\/authService.js:21:67)
    at tryCatch (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:17)
    at _next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:17:9)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
[2024-10-04 11:17:03] [[31merror[39m] TypeError: Cannot read properties of null (reading 'password')
    at _callee$ (C:\My project\My project\back-end\src\services\/authService.js:21:67)
    at tryCatch (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:17)
    at _next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:17:9)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
[2024-10-04 11:17:25] [[31merror[39m] TypeError: Cannot read properties of null (reading 'password')
    at _callee$ (C:\My project\My project\back-end\src\services\/authService.js:21:67)
    at tryCatch (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:17)
    at _next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:17:9)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
[2024-10-04 11:17:51] [[31merror[39m] TypeError: Cannot read properties of null (reading 'password')
    at _callee$ (C:\My project\My project\back-end\src\services\/authService.js:21:67)
    at tryCatch (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:17)
    at _next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:17:9)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
[2024-10-04 11:20:29] [[31merror[39m] TypeError: Cannot read properties of null (reading 'password')
    at _callee$ (C:\My project\My project\back-end\src\services\/authService.js:21:67)
    at tryCatch (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:17)
    at _next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:17:9)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
[2024-10-04 11:22:30] [[31merror[39m] TypeError: Cannot read properties of null (reading 'password')
    at _callee$ (C:\My project\My project\back-end\src\services\/authService.js:21:67)
    at tryCatch (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:17)
    at _next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:17:9)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
[2024-10-04 11:22:31] [[31merror[39m] TypeError: Cannot read properties of null (reading 'password')
    at _callee$ (C:\My project\My project\back-end\src\services\/authService.js:21:67)
    at tryCatch (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:17)
    at _next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:17:9)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
[2024-10-04 11:22:35] [[31merror[39m] TypeError: Cannot read properties of null (reading 'password')
    at _callee$ (C:\My project\My project\back-end\src\services\/authService.js:21:67)
    at tryCatch (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:17)
    at _next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:17:9)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
[2024-10-04 11:22:55] [[31merror[39m] TypeError: Cannot read properties of null (reading 'password')
    at _callee$ (C:\My project\My project\back-end\src\services\/authService.js:21:67)
    at tryCatch (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:17)
    at _next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:17:9)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
[2024-10-04 11:23:11] [[31merror[39m] TypeError: Cannot read properties of null (reading 'password')
    at _callee$ (C:\My project\My project\back-end\src\services\/authService.js:21:67)
    at tryCatch (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:17)
    at _next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:17:9)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
[2024-10-04 11:24:34] [[31merror[39m] TypeError: Cannot read properties of null (reading 'password')
    at _callee$ (C:\My project\My project\back-end\src\services\/authService.js:21:67)
    at tryCatch (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:17)
    at _next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:17:9)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
[2024-10-04 11:25:55] [[31merror[39m] TypeError: Cannot read properties of null (reading 'password')
    at _callee$ (C:\My project\My project\back-end\src\services\/authService.js:21:67)
    at tryCatch (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:17)
    at _next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:17:9)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
[2024-10-04 11:26:16] [[31merror[39m] TypeError: Cannot read properties of null (reading 'password')
    at _callee$ (C:\My project\My project\back-end\src\services\/authService.js:21:67)
    at tryCatch (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:17)
    at _next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:17:9)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
[2024-10-04 11:26:52] [[31merror[39m] TypeError: Cannot read properties of null (reading 'password')
    at _callee$ (C:\My project\My project\back-end\src\services\/authService.js:21:67)
    at tryCatch (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:17)
    at _next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:17:9)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
[2024-10-04 13:47:33] [[31merror[39m] TypeError: Cannot read properties of null (reading 'password')
    at _callee$ (C:\My project\My project\back-end\src\services\/authService.js:21:67)
    at tryCatch (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:17)
    at _next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:17:9)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
[2024-10-04 16:02:35] [[31merror[39m] TypeError: result.get is not a function
    at C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1885:39
    at Array.reduce (<anonymous>)
    at C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1884:19
    at Array.map (<anonymous>)
    at Function._findSeparate (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1881:39)
    at Function.findAll (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1840:24)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Promise.all (index 1)
    at Function.findAndCountAll (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:2183:27)
[2024-10-04 16:02:49] [[31merror[39m] TypeError: result.get is not a function
    at C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1885:39
    at Array.reduce (<anonymous>)
    at C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1884:19
    at Array.map (<anonymous>)
    at Function._findSeparate (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1881:39)
    at Function.findAll (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1840:24)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Promise.all (index 1)
    at Function.findAndCountAll (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:2183:27)
[2024-10-04 16:03:08] [[31merror[39m] TypeError: _models.default.Kanji.fillAll is not a function
    at _callee2$ (C:\My project\My project\back-end\src\services\/kanjiService.js:65:39)
    at tryCatch (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:17)
    at _next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:17:9)
    at C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:7
    at new Promise (<anonymous>)
    at apply (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:14:12)
    at C:\My project\My project\back-end\src\services\/kanjiService.js:80:6
    at new Promise (<anonymous>)
    at Object.getListKanji (C:\My project\My project\back-end\src\services\/kanjiService.js:37:12)
    at _callee2$ (C:\My project\My project\back-end\src\controllers\/kanjiController.js:25:52)
    at tryCatch (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:17)
    at _next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:17:9)
    at C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:7
    at new Promise (<anonymous>)
    at apply (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:14:12)
    at getListKanji (C:\My project\My project\back-end\src\controllers\/kanjiController.js:22:15)
    at Layer.handle [as handle_request] (C:\My project\My project\back-end\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\My project\My project\back-end\node_modules\express\lib\router\route.js:149:13)
    at verifyToken (C:\My project\My project\back-end\src\middleware\/tokenMiddleware.js:16:5)
    at Layer.handle [as handle_request] (C:\My project\My project\back-end\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\My project\My project\back-end\node_modules\express\lib\router\route.js:149:13)
    at Route.dispatch (C:\My project\My project\back-end\node_modules\express\lib\router\route.js:119:3)
    at Layer.handle [as handle_request] (C:\My project\My project\back-end\node_modules\express\lib\router\layer.js:95:5)
    at C:\My project\My project\back-end\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (C:\My project\My project\back-end\node_modules\express\lib\router\index.js:346:12)
    at next (C:\My project\My project\back-end\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\My project\My project\back-end\node_modules\express\lib\router\index.js:175:3)
    at router (C:\My project\My project\back-end\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\My project\My project\back-end\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\My project\My project\back-end\node_modules\express\lib\router\index.js:328:13)
    at C:\My project\My project\back-end\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\My project\My project\back-end\node_modules\express\lib\router\index.js:346:12)
    at next (C:\My project\My project\back-end\node_modules\express\lib\router\index.js:280:10)
    at C:\My project\My project\back-end\node_modules\express\lib\router\index.js:646:15
    at next (C:\My project\My project\back-end\node_modules\express\lib\router\index.js:265:14)
    at Function.handle (C:\My project\My project\back-end\node_modules\express\lib\router\index.js:175:3)
    at router (C:\My project\My project\back-end\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\My project\My project\back-end\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\My project\My project\back-end\node_modules\express\lib\router\index.js:328:13)
    at C:\My project\My project\back-end\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\My project\My project\back-end\node_modules\express\lib\router\index.js:346:12)
    at next (C:\My project\My project\back-end\node_modules\express\lib\router\index.js:280:10)
    at SendStream.error (C:\My project\My project\back-end\node_modules\serve-static\index.js:121:7)
    at SendStream.emit (node:events:520:28)
[2024-10-04 16:05:00] [[31merror[39m] TypeError: result.get is not a function
    at C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1885:39
    at Array.reduce (<anonymous>)
    at C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1884:19
    at Array.map (<anonymous>)
    at Function._findSeparate (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1881:39)
    at Function.findAll (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1840:24)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Promise.all (index 1)
    at Function.findAndCountAll (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:2183:27)
[2024-10-04 16:05:52] [[31merror[39m] TypeError: result.get is not a function
    at C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1885:39
    at Array.reduce (<anonymous>)
    at C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1884:19
    at Array.map (<anonymous>)
    at Function._findSeparate (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1881:39)
    at Function.findAll (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1840:24)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Promise.all (index 1)
    at Function.findAndCountAll (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:2183:27)
[2024-10-04 16:06:47] [[31merror[39m] SequelizeEagerLoadingError: ExampleKanji is associated to Kanji using an alias. You've included an alias (examples), but it does not match the alias(es) defined in your association (ExampleKanjis).
    at Function._getIncludedAssociation (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:751:15)
    at Function._validateIncludedElement (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:646:53)
    at C:\My project\My project\back-end\node_modules\sequelize\src\model.js:542:37
    at Array.map (<anonymous>)
    at Function._validateIncludedElements (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:537:39)
    at Function.aggregate (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:2030:12)
    at Function.count (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:2124:31)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Promise.all (index 0)
    at Function.findAndCountAll (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:2183:27)
[2024-10-04 16:09:01] [[31merror[39m] TypeError: result.get is not a function
    at C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1885:39
    at Array.reduce (<anonymous>)
    at C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1884:19
    at Array.map (<anonymous>)
    at Function._findSeparate (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1881:39)
    at Function.findAll (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1840:24)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Promise.all (index 1)
    at Function.findAndCountAll (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:2183:27)
[2024-10-04 16:12:22] [[31merror[39m] TypeError: result.get is not a function
    at C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1885:39
    at Array.reduce (<anonymous>)
    at C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1884:19
    at Array.map (<anonymous>)
    at Function._findSeparate (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1881:39)
    at Function.findAll (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1840:24)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Promise.all (index 1)
    at Function.findAndCountAll (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:2183:27)
[2024-10-04 16:13:28] [[31merror[39m] TypeError: result.get is not a function
    at C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1885:39
    at Array.reduce (<anonymous>)
    at C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1884:19
    at Array.map (<anonymous>)
    at Function._findSeparate (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1881:39)
    at Function.findAll (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1840:24)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Promise.all (index 1)
    at Function.findAndCountAll (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:2183:27)
[2024-10-07 09:49:06] [[31merror[39m] Error: 
    at Query.run (C:\My project\My project\back-end\node_modules\sequelize\src\dialects\mysql\query.js:46:25)
    at C:\My project\My project\back-end\node_modules\sequelize\src\sequelize.js:650:28
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at MySQLQueryInterface.select (C:\My project\My project\back-end\node_modules\sequelize\src\dialects\abstract\query-interface.js:1001:12)
    at Function.findAll (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1824:21)
    at Function.findOne (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1998:12)
[2024-10-07 09:49:30] [[31merror[39m] Error: 
    at Query.run (C:\My project\My project\back-end\node_modules\sequelize\src\dialects\mysql\query.js:46:25)
    at C:\My project\My project\back-end\node_modules\sequelize\src\sequelize.js:650:28
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at MySQLQueryInterface.select (C:\My project\My project\back-end\node_modules\sequelize\src\dialects\abstract\query-interface.js:1001:12)
    at Function.findAll (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1824:21)
    at Function.findOne (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1998:12)
[2024-10-07 09:49:37] [[31merror[39m] Error: 
    at Query.run (C:\My project\My project\back-end\node_modules\sequelize\src\dialects\mysql\query.js:46:25)
    at C:\My project\My project\back-end\node_modules\sequelize\src\sequelize.js:650:28
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at MySQLQueryInterface.select (C:\My project\My project\back-end\node_modules\sequelize\src\dialects\abstract\query-interface.js:1001:12)
    at Function.findAll (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1824:21)
    at Function.findOne (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1998:12)
[2024-10-07 09:49:48] [[31merror[39m] Error: 
    at Query.run (C:\My project\My project\back-end\node_modules\sequelize\src\dialects\mysql\query.js:46:25)
    at C:\My project\My project\back-end\node_modules\sequelize\src\sequelize.js:650:28
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at MySQLQueryInterface.select (C:\My project\My project\back-end\node_modules\sequelize\src\dialects\abstract\query-interface.js:1001:12)
    at Function.findAll (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1824:21)
    at Function.findOne (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1998:12)
[2024-10-07 11:30:59] [[31merror[39m] TypeError: Cannot read properties of null (reading 'password')
    at _callee$ (C:\My project\My project\back-end\src\services\/authService.js:21:67)
    at tryCatch (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:17)
    at _next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:17:9)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
[2024-10-07 16:08:16] [[31merror[39m] TypeError: Cannot read properties of undefined (reading 'join')
    at map (C:\My project\My project\back-end\src\services\/examService.js:105:41)
    at Array.map (<anonymous>)
    at _callee3$ (C:\My project\My project\back-end\src\services\/examService.js:102:25)
    at tryCatch (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:17)
    at _next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:17:9)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
[2024-10-07 16:08:32] [[31merror[39m] Error: 
    at Query.run (C:\My project\My project\back-end\node_modules\sequelize\src\dialects\mysql\query.js:46:25)
    at C:\My project\My project\back-end\node_modules\sequelize\src\sequelize.js:650:28
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at MySQLQueryInterface.insert (C:\My project\My project\back-end\node_modules\sequelize\src\dialects\abstract\query-interface.js:795:21)
    at Exam.save (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:4154:35)
    at Function.create (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:2305:12)
[2024-10-07 16:09:01] [[31merror[39m] Error: 
    at Query.run (C:\My project\My project\back-end\node_modules\sequelize\src\dialects\mysql\query.js:46:25)
    at C:\My project\My project\back-end\node_modules\sequelize\src\sequelize.js:650:28
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at MySQLQueryInterface.insert (C:\My project\My project\back-end\node_modules\sequelize\src\dialects\abstract\query-interface.js:795:21)
    at Exam.save (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:4154:35)
    at Function.create (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:2305:12)
[2024-10-07 16:09:46] [[31merror[39m] Error: 
    at Query.run (C:\My project\My project\back-end\node_modules\sequelize\src\dialects\mysql\query.js:46:25)
    at C:\My project\My project\back-end\node_modules\sequelize\src\sequelize.js:650:28
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at MySQLQueryInterface.insert (C:\My project\My project\back-end\node_modules\sequelize\src\dialects\abstract\query-interface.js:795:21)
    at Exam.save (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:4154:35)
    at Function.create (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:2305:12)
[2024-10-07 16:10:48] [[31merror[39m] TypeError: Cannot read properties of undefined (reading 'join')
    at map (C:\My project\My project\back-end\src\services\/examService.js:107:41)
    at Array.map (<anonymous>)
    at _callee3$ (C:\My project\My project\back-end\src\services\/examService.js:104:25)
    at tryCatch (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:17)
    at _next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:17:9)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
[2024-10-07 16:12:48] [[31merror[39m] TypeError: Cannot read properties of undefined (reading 'join')
    at map (C:\My project\My project\back-end\src\services\/examService.js:107:41)
    at Array.map (<anonymous>)
    at _callee3$ (C:\My project\My project\back-end\src\services\/examService.js:104:25)
    at tryCatch (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:17)
    at _next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:17:9)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
[2024-10-07 16:14:40] [[31merror[39m] TypeError: result.get is not a function
    at C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1885:39
    at Array.reduce (<anonymous>)
    at C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1884:19
    at Array.map (<anonymous>)
    at Function._findSeparate (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1881:39)
    at Function.findAll (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1840:24)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at Function.findOne (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1998:12)
    at Function.findByPk (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1955:12)
[2024-10-07 16:15:23] [[31merror[39m] TypeError: result.get is not a function
    at C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1885:39
    at Array.reduce (<anonymous>)
    at C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1884:19
    at Array.map (<anonymous>)
    at Function._findSeparate (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1881:39)
    at Function.findAll (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1840:24)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at Function.findOne (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1998:12)
    at Function.findByPk (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1955:12)
[2024-10-07 16:18:36] [[31merror[39m] TypeError: item.questions.map is not a function
    at map (C:\My project\My project\back-end\src\services\/examService.js:76:41)
    at Array.map (<anonymous>)
    at _callee2$ (C:\My project\My project\back-end\src\services\/examService.js:74:24)
    at tryCatch (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:17)
    at _next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:17:9)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
[2024-10-07 16:19:11] [[31merror[39m] TypeError: item.questions.map is not a function
    at map (C:\My project\My project\back-end\src\services\/examService.js:77:41)
    at Array.map (<anonymous>)
    at _callee2$ (C:\My project\My project\back-end\src\services\/examService.js:75:24)
    at tryCatch (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:17)
    at _next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:17:9)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
[2024-10-07 16:19:58] [[31merror[39m] ReferenceError: groupAndMerge is not defined
    at _callee2$ (C:\My project\My project\back-end\src\services\/examService.js:72:15)
    at tryCatch (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:17)
    at _next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:17:9)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
[2024-10-07 16:20:11] [[31merror[39m] TypeError: item.questions.map is not a function
    at map (C:\My project\My project\back-end\src\services\/examService.js:79:41)
    at Array.map (<anonymous>)
    at _callee2$ (C:\My project\My project\back-end\src\services\/examService.js:77:24)
    at tryCatch (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:17)
    at _next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:17:9)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
[2024-10-08 08:58:49] [[31merror[39m] SequelizeConnectionError: connect ETIMEDOUT
    at ConnectionManager.connect (C:\My project\My project\back-end\node_modules\sequelize\src\dialects\mysql\connection-manager.js:126:17)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at ConnectionManager._connect (C:\My project\My project\back-end\node_modules\sequelize\src\dialects\abstract\connection-manager.js:332:24)
    at C:\My project\My project\back-end\node_modules\sequelize\src\dialects\abstract\connection-manager.js:250:32
    at ConnectionManager.getConnection (C:\My project\My project\back-end\node_modules\sequelize\src\dialects\abstract\connection-manager.js:280:7)
    at C:\My project\My project\back-end\node_modules\sequelize\src\sequelize.js:638:26
    at MySQLQueryInterface.select (C:\My project\My project\back-end\node_modules\sequelize\src\dialects\abstract\query-interface.js:1001:12)
    at Function.findAll (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1824:21)
    at Function.findOne (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1998:12)
[2024-10-08 08:58:49] [[31merror[39m] SequelizeConnectionError: connect ETIMEDOUT
    at ConnectionManager.connect (C:\My project\My project\back-end\node_modules\sequelize\src\dialects\mysql\connection-manager.js:126:17)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at ConnectionManager._connect (C:\My project\My project\back-end\node_modules\sequelize\src\dialects\abstract\connection-manager.js:332:24)
    at C:\My project\My project\back-end\node_modules\sequelize\src\dialects\abstract\connection-manager.js:250:32
    at ConnectionManager.getConnection (C:\My project\My project\back-end\node_modules\sequelize\src\dialects\abstract\connection-manager.js:280:7)
    at C:\My project\My project\back-end\node_modules\sequelize\src\sequelize.js:638:26
    at MySQLQueryInterface.select (C:\My project\My project\back-end\node_modules\sequelize\src\dialects\abstract\query-interface.js:1001:12)
    at Function.findAll (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1824:21)
    at Function.findOne (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1998:12)
[2024-10-08 08:59:05] [[31merror[39m] SequelizeConnectionError: connect ETIMEDOUT
    at ConnectionManager.connect (C:\My project\My project\back-end\node_modules\sequelize\src\dialects\mysql\connection-manager.js:126:17)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at ConnectionManager._connect (C:\My project\My project\back-end\node_modules\sequelize\src\dialects\abstract\connection-manager.js:332:24)
    at C:\My project\My project\back-end\node_modules\sequelize\src\dialects\abstract\connection-manager.js:250:32
    at ConnectionManager.getConnection (C:\My project\My project\back-end\node_modules\sequelize\src\dialects\abstract\connection-manager.js:280:7)
    at C:\My project\My project\back-end\node_modules\sequelize\src\sequelize.js:638:26
    at MySQLQueryInterface.select (C:\My project\My project\back-end\node_modules\sequelize\src\dialects\abstract\query-interface.js:1001:12)
    at Function.findAll (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1824:21)
    at Function.findOne (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1998:12)
[2024-10-08 08:59:05] [[31merror[39m] SequelizeConnectionError: connect ETIMEDOUT
    at ConnectionManager.connect (C:\My project\My project\back-end\node_modules\sequelize\src\dialects\mysql\connection-manager.js:126:17)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at ConnectionManager._connect (C:\My project\My project\back-end\node_modules\sequelize\src\dialects\abstract\connection-manager.js:332:24)
    at C:\My project\My project\back-end\node_modules\sequelize\src\dialects\abstract\connection-manager.js:250:32
    at ConnectionManager.getConnection (C:\My project\My project\back-end\node_modules\sequelize\src\dialects\abstract\connection-manager.js:280:7)
    at C:\My project\My project\back-end\node_modules\sequelize\src\sequelize.js:638:26
    at MySQLQueryInterface.select (C:\My project\My project\back-end\node_modules\sequelize\src\dialects\abstract\query-interface.js:1001:12)
    at Function.findAll (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1824:21)
    at Function.findOne (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1998:12)
[2024-10-08 08:59:23] [[31merror[39m] SequelizeConnectionError: connect ETIMEDOUT
    at ConnectionManager.connect (C:\My project\My project\back-end\node_modules\sequelize\src\dialects\mysql\connection-manager.js:126:17)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at ConnectionManager._connect (C:\My project\My project\back-end\node_modules\sequelize\src\dialects\abstract\connection-manager.js:332:24)
    at C:\My project\My project\back-end\node_modules\sequelize\src\dialects\abstract\connection-manager.js:250:32
    at ConnectionManager.getConnection (C:\My project\My project\back-end\node_modules\sequelize\src\dialects\abstract\connection-manager.js:280:7)
    at C:\My project\My project\back-end\node_modules\sequelize\src\sequelize.js:638:26
    at MySQLQueryInterface.select (C:\My project\My project\back-end\node_modules\sequelize\src\dialects\abstract\query-interface.js:1001:12)
    at Function.findAll (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1824:21)
    at Function.findOne (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1998:12)
[2024-10-08 08:59:23] [[31merror[39m] SequelizeConnectionError: connect ETIMEDOUT
    at ConnectionManager.connect (C:\My project\My project\back-end\node_modules\sequelize\src\dialects\mysql\connection-manager.js:126:17)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at ConnectionManager._connect (C:\My project\My project\back-end\node_modules\sequelize\src\dialects\abstract\connection-manager.js:332:24)
    at C:\My project\My project\back-end\node_modules\sequelize\src\dialects\abstract\connection-manager.js:250:32
    at ConnectionManager.getConnection (C:\My project\My project\back-end\node_modules\sequelize\src\dialects\abstract\connection-manager.js:280:7)
    at C:\My project\My project\back-end\node_modules\sequelize\src\sequelize.js:638:26
    at MySQLQueryInterface.select (C:\My project\My project\back-end\node_modules\sequelize\src\dialects\abstract\query-interface.js:1001:12)
    at Function.findAll (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1824:21)
    at Function.findOne (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1998:12)
[2024-10-08 11:43:21] [[31merror[39m] TypeError: Cannot read properties of undefined (reading 'questions')
    at _callee2$ (C:\My project\My project\back-end\src\services\/examService.js:79:36)
    at tryCatch (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:17)
    at _next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:17:9)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
[2024-10-08 14:50:37] [[31merror[39m] ReferenceError: onRemoveParams is not defined
    at _callee2$ (C:\My project\My project\back-end\src\services\/testService.js:44:15)
    at tryCatch (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:17)
    at _next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:17:9)
    at C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:7
    at new Promise (<anonymous>)
    at apply (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:14:12)
    at C:\My project\My project\back-end\src\services\/testService.js:78:6
    at new Promise (<anonymous>)
    at Object.getAllScoresTest (C:\My project\My project\back-end\src\services\/testService.js:33:12)
    at _callee2$ (C:\My project\My project\back-end\src\controllers\/testController.js:21:51)
    at tryCatch (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:17)
    at _next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:17:9)
    at C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:7
    at new Promise (<anonymous>)
    at apply (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:14:12)
    at getAllScoresTest (C:\My project\My project\back-end\src\controllers\/testController.js:17:19)
    at Layer.handle [as handle_request] (C:\My project\My project\back-end\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\My project\My project\back-end\node_modules\express\lib\router\route.js:149:13)
    at verifyToken (C:\My project\My project\back-end\src\middleware\/tokenMiddleware.js:16:5)
    at Layer.handle [as handle_request] (C:\My project\My project\back-end\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\My project\My project\back-end\node_modules\express\lib\router\route.js:149:13)
    at Route.dispatch (C:\My project\My project\back-end\node_modules\express\lib\router\route.js:119:3)
    at Layer.handle [as handle_request] (C:\My project\My project\back-end\node_modules\express\lib\router\layer.js:95:5)
    at C:\My project\My project\back-end\node_modules\express\lib\router\index.js:284:15
    at param (C:\My project\My project\back-end\node_modules\express\lib\router\index.js:365:14)
    at param (C:\My project\My project\back-end\node_modules\express\lib\router\index.js:376:14)
    at Function.process_params (C:\My project\My project\back-end\node_modules\express\lib\router\index.js:421:3)
    at next (C:\My project\My project\back-end\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\My project\My project\back-end\node_modules\express\lib\router\index.js:175:3)
    at router (C:\My project\My project\back-end\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\My project\My project\back-end\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\My project\My project\back-end\node_modules\express\lib\router\index.js:328:13)
    at C:\My project\My project\back-end\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\My project\My project\back-end\node_modules\express\lib\router\index.js:346:12)
    at next (C:\My project\My project\back-end\node_modules\express\lib\router\index.js:280:10)
    at C:\My project\My project\back-end\node_modules\express\lib\router\index.js:646:15
    at next (C:\My project\My project\back-end\node_modules\express\lib\router\index.js:265:14)
    at Function.handle (C:\My project\My project\back-end\node_modules\express\lib\router\index.js:175:3)
    at router (C:\My project\My project\back-end\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\My project\My project\back-end\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\My project\My project\back-end\node_modules\express\lib\router\index.js:328:13)
    at C:\My project\My project\back-end\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\My project\My project\back-end\node_modules\express\lib\router\index.js:346:12)
    at next (C:\My project\My project\back-end\node_modules\express\lib\router\index.js:280:10)
[2024-10-08 14:51:39] [[31merror[39m] SequelizeEagerLoadingError: UserExam is not associated to Kanji!
    at Function._getIncludedAssociation (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:742:13)
    at Function._validateIncludedElement (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:646:53)
    at C:\My project\My project\back-end\node_modules\sequelize\src\model.js:542:37
    at Array.map (<anonymous>)
    at Function._validateIncludedElements (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:537:39)
    at Function.aggregate (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:2030:12)
    at Function.count (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:2124:31)
    at async Promise.all (index 0)
    at Function.findAndCountAll (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:2183:27)
[2024-10-08 14:52:06] [[31merror[39m] SequelizeEagerLoadingError: UserExam is associated to Exam using an alias. You've included an alias (userExams), but it does not match the alias(es) defined in your association (UserExams).
    at Function._getIncludedAssociation (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:751:15)
    at Function._validateIncludedElement (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:646:53)
    at C:\My project\My project\back-end\node_modules\sequelize\src\model.js:542:37
    at Array.map (<anonymous>)
    at Function._validateIncludedElements (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:537:39)
    at Function.aggregate (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:2030:12)
    at Function.count (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:2124:31)
    at async Promise.all (index 0)
    at Function.findAndCountAll (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:2183:27)
[2024-10-08 14:52:53] [[31merror[39m] Error: WHERE parameter "idUser" has invalid "undefined" value
    at MySQLQueryGenerator.whereItemQuery (C:\My project\My project\back-end\node_modules\sequelize\src\dialects\abstract\query-generator.js:2445:13)
    at C:\My project\My project\back-end\node_modules\sequelize\src\dialects\abstract\query-generator.js:2434:25
    at Array.forEach (<anonymous>)
    at MySQLQueryGenerator.whereItemsQuery (C:\My project\My project\back-end\node_modules\sequelize\src\dialects\abstract\query-generator.js:2432:35)
    at MySQLQueryGenerator.generateJoin (C:\My project\My project\back-end\node_modules\sequelize\src\dialects\abstract\query-generator.js:1871:24)
    at MySQLQueryGenerator.generateInclude (C:\My project\My project\back-end\node_modules\sequelize\src\dialects\abstract\query-generator.js:1708:24)
    at MySQLQueryGenerator.selectQuery (C:\My project\My project\back-end\node_modules\sequelize\src\dialects\abstract\query-generator.js:1322:34)
    at MySQLQueryInterface.rawSelect (C:\My project\My project\back-end\node_modules\sequelize\src\dialects\abstract\query-interface.js:1037:37)
    at Function.aggregate (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:2067:45)
    at Function.count (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:2124:31)
    at async Promise.all (index 0)
    at Function.findAndCountAll (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:2183:27)
[2024-10-08 14:53:25] [[31merror[39m] Error: WHERE parameter "idUser" has invalid "undefined" value
    at MySQLQueryGenerator.whereItemQuery (C:\My project\My project\back-end\node_modules\sequelize\src\dialects\abstract\query-generator.js:2445:13)
    at C:\My project\My project\back-end\node_modules\sequelize\src\dialects\abstract\query-generator.js:2434:25
    at Array.forEach (<anonymous>)
    at MySQLQueryGenerator.whereItemsQuery (C:\My project\My project\back-end\node_modules\sequelize\src\dialects\abstract\query-generator.js:2432:35)
    at MySQLQueryGenerator.generateJoin (C:\My project\My project\back-end\node_modules\sequelize\src\dialects\abstract\query-generator.js:1871:24)
    at MySQLQueryGenerator.generateInclude (C:\My project\My project\back-end\node_modules\sequelize\src\dialects\abstract\query-generator.js:1708:24)
    at MySQLQueryGenerator.selectQuery (C:\My project\My project\back-end\node_modules\sequelize\src\dialects\abstract\query-generator.js:1322:34)
    at MySQLQueryInterface.rawSelect (C:\My project\My project\back-end\node_modules\sequelize\src\dialects\abstract\query-interface.js:1037:37)
    at Function.aggregate (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:2067:45)
    at Function.count (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:2124:31)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Promise.all (index 0)
    at Function.findAndCountAll (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:2183:27)
[2024-10-08 14:53:47] [[31merror[39m] ReferenceError: groupAndMerge is not defined
    at _callee2$ (C:\My project\My project\back-end\src\services\/testService.js:69:15)
    at tryCatch (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:17)
    at _next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:17:9)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
[2024-10-08 14:54:06] [[31merror[39m] ReferenceError: groupAndMerge is not defined
    at _callee2$ (C:\My project\My project\back-end\src\services\/testService.js:70:15)
    at tryCatch (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:17)
    at _next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:17:9)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
[2024-10-08 14:56:40] [[31merror[39m] ReferenceError: groupAndMerge is not defined
    at _callee2$ (C:\My project\My project\back-end\src\services\/testService.js:71:15)
    at tryCatch (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:17)
    at _next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:17:9)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
[2024-10-08 14:57:53] [[31merror[39m] ReferenceError: groupAndMerge is not defined
    at _callee2$ (C:\My project\My project\back-end\src\services\/testService.js:68:15)
    at tryCatch (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:17)
    at _next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:17:9)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
[2024-10-08 16:15:32] [[31merror[39m] ReferenceError: UserExam is not defined
    at _callee3$ (C:\My project\My project\back-end\src\services\/testService.js:80:46)
    at tryCatch (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:17)
    at _next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:17:9)
    at C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:7
    at new Promise (<anonymous>)
    at apply (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:14:12)
    at C:\My project\My project\back-end\src\services\/testService.js:105:6
    at new Promise (<anonymous>)
    at Object.getProcess (C:\My project\My project\back-end\src\services\/testService.js:80:12)
    at _callee3$ (C:\My project\My project\back-end\src\controllers\/testController.js:35:51)
    at tryCatch (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:17)
    at _next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:17:9)
    at C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:7
    at new Promise (<anonymous>)
    at apply (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:14:12)
    at getProcess (C:\My project\My project\back-end\src\controllers\/testController.js:32:13)
    at Layer.handle [as handle_request] (C:\My project\My project\back-end\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\My project\My project\back-end\node_modules\express\lib\router\route.js:149:13)
    at verifyToken (C:\My project\My project\back-end\src\middleware\/tokenMiddleware.js:16:5)
    at Layer.handle [as handle_request] (C:\My project\My project\back-end\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\My project\My project\back-end\node_modules\express\lib\router\route.js:149:13)
    at Route.dispatch (C:\My project\My project\back-end\node_modules\express\lib\router\route.js:119:3)
    at Layer.handle [as handle_request] (C:\My project\My project\back-end\node_modules\express\lib\router\layer.js:95:5)
    at C:\My project\My project\back-end\node_modules\express\lib\router\index.js:284:15
    at param (C:\My project\My project\back-end\node_modules\express\lib\router\index.js:365:14)
    at param (C:\My project\My project\back-end\node_modules\express\lib\router\index.js:376:14)
    at Function.process_params (C:\My project\My project\back-end\node_modules\express\lib\router\index.js:421:3)
    at next (C:\My project\My project\back-end\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\My project\My project\back-end\node_modules\express\lib\router\index.js:175:3)
    at router (C:\My project\My project\back-end\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\My project\My project\back-end\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\My project\My project\back-end\node_modules\express\lib\router\index.js:328:13)
    at C:\My project\My project\back-end\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\My project\My project\back-end\node_modules\express\lib\router\index.js:346:12)
    at next (C:\My project\My project\back-end\node_modules\express\lib\router\index.js:280:10)
    at C:\My project\My project\back-end\node_modules\express\lib\router\index.js:646:15
    at next (C:\My project\My project\back-end\node_modules\express\lib\router\index.js:265:14)
    at Function.handle (C:\My project\My project\back-end\node_modules\express\lib\router\index.js:175:3)
    at router (C:\My project\My project\back-end\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\My project\My project\back-end\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\My project\My project\back-end\node_modules\express\lib\router\index.js:328:13)
    at C:\My project\My project\back-end\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\My project\My project\back-end\node_modules\express\lib\router\index.js:346:12)
    at next (C:\My project\My project\back-end\node_modules\express\lib\router\index.js:280:10)
[2024-10-08 16:15:51] [[31merror[39m] ReferenceError: Exam is not defined
    at _callee3$ (C:\My project\My project\back-end\src\services\/testService.js:88:20)
    at tryCatch (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:17)
    at _next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:17:9)
    at C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:7
    at new Promise (<anonymous>)
    at apply (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:14:12)
    at C:\My project\My project\back-end\src\services\/testService.js:105:6
    at new Promise (<anonymous>)
    at Object.getProcess (C:\My project\My project\back-end\src\services\/testService.js:80:12)
    at _callee3$ (C:\My project\My project\back-end\src\controllers\/testController.js:35:51)
    at tryCatch (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:17)
    at _next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:17:9)
    at C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:7
    at new Promise (<anonymous>)
    at apply (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:14:12)
    at getProcess (C:\My project\My project\back-end\src\controllers\/testController.js:32:13)
    at Layer.handle [as handle_request] (C:\My project\My project\back-end\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\My project\My project\back-end\node_modules\express\lib\router\route.js:149:13)
    at verifyToken (C:\My project\My project\back-end\src\middleware\/tokenMiddleware.js:16:5)
    at Layer.handle [as handle_request] (C:\My project\My project\back-end\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\My project\My project\back-end\node_modules\express\lib\router\route.js:149:13)
    at Route.dispatch (C:\My project\My project\back-end\node_modules\express\lib\router\route.js:119:3)
    at Layer.handle [as handle_request] (C:\My project\My project\back-end\node_modules\express\lib\router\layer.js:95:5)
    at C:\My project\My project\back-end\node_modules\express\lib\router\index.js:284:15
    at param (C:\My project\My project\back-end\node_modules\express\lib\router\index.js:365:14)
    at param (C:\My project\My project\back-end\node_modules\express\lib\router\index.js:376:14)
    at Function.process_params (C:\My project\My project\back-end\node_modules\express\lib\router\index.js:421:3)
    at next (C:\My project\My project\back-end\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\My project\My project\back-end\node_modules\express\lib\router\index.js:175:3)
    at router (C:\My project\My project\back-end\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\My project\My project\back-end\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\My project\My project\back-end\node_modules\express\lib\router\index.js:328:13)
    at C:\My project\My project\back-end\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\My project\My project\back-end\node_modules\express\lib\router\index.js:346:12)
    at next (C:\My project\My project\back-end\node_modules\express\lib\router\index.js:280:10)
    at C:\My project\My project\back-end\node_modules\express\lib\router\index.js:646:15
    at next (C:\My project\My project\back-end\node_modules\express\lib\router\index.js:265:14)
    at Function.handle (C:\My project\My project\back-end\node_modules\express\lib\router\index.js:175:3)
    at router (C:\My project\My project\back-end\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\My project\My project\back-end\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\My project\My project\back-end\node_modules\express\lib\router\index.js:328:13)
    at C:\My project\My project\back-end\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\My project\My project\back-end\node_modules\express\lib\router\index.js:346:12)
    at next (C:\My project\My project\back-end\node_modules\express\lib\router\index.js:280:10)
[2024-10-08 16:16:11] [[31merror[39m] SequelizeEagerLoadingError: Exam is associated to UserExam using an alias. You must use the 'as' keyword to specify the alias within your include statement.
    at Function._getIncludedAssociation (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:754:13)
    at Function._validateIncludedElement (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:646:53)
    at C:\My project\My project\back-end\node_modules\sequelize\src\model.js:542:37
    at Array.map (<anonymous>)
    at Function._validateIncludedElements (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:537:39)
    at Function.findAll (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1794:12)
[2024-10-08 16:16:50] [[31merror[39m] TypeError: result.get is not a function
    at C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1885:39
    at Array.reduce (<anonymous>)
    at C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1884:19
    at Array.map (<anonymous>)
    at Function._findSeparate (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1881:39)
    at Function.findAll (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1840:24)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
[2024-10-08 16:17:41] [[31merror[39m] TypeError: result.get is not a function
    at C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1885:39
    at Array.reduce (<anonymous>)
    at C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1884:19
    at Array.map (<anonymous>)
    at Function._findSeparate (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1881:39)
    at Function.findAll (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1840:24)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
[2024-10-08 16:17:49] [[31merror[39m] TypeError: result.get is not a function
    at C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1885:39
    at Array.reduce (<anonymous>)
    at C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1884:19
    at Array.map (<anonymous>)
    at Function._findSeparate (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1881:39)
    at Function.findAll (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1840:24)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
[2024-10-08 16:18:26] [[31merror[39m] TypeError: result.get is not a function
    at C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1885:39
    at Array.reduce (<anonymous>)
    at C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1884:19
    at Array.map (<anonymous>)
    at Function._findSeparate (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1881:39)
    at Function.findAll (C:\My project\My project\back-end\node_modules\sequelize\src\model.js:1840:24)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
[2024-10-08 16:24:53] [[31merror[39m] ReferenceError: Exam is not defined
    at _callee3$ (C:\My project\My project\back-end\src\services\/testService.js:82:22)
    at tryCatch (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:17)
    at _next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:17:9)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
[2024-10-08 16:25:07] [[31merror[39m] ReferenceError: sequelize is not defined
    at _callee3$ (C:\My project\My project\back-end\src\services\/testService.js:103:14)
    at tryCatch (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:17)
    at _next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:17:9)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
[2024-10-08 16:25:17] [[31merror[39m] ReferenceError: sequelize is not defined
    at _callee3$ (C:\My project\My project\back-end\src\services\/testService.js:103:14)
    at tryCatch (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:17)
    at _next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:17:9)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
[2024-10-08 16:25:32] [[31merror[39m] TypeError: result.get is not a function
    at map (C:\My project\My project\back-end\src\services\/testService.js:110:25)
    at Array.map (<anonymous>)
    at _callee3$ (C:\My project\My project\back-end\src\services\/testService.js:108:37)
    at tryCatch (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:17)
    at _next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:17:9)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
[2024-10-08 16:25:41] [[31merror[39m] TypeError: result.get is not a function
    at map (C:\My project\My project\back-end\src\services\/testService.js:112:25)
    at Array.map (<anonymous>)
    at _callee3$ (C:\My project\My project\back-end\src\services\/testService.js:110:37)
    at tryCatch (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:17)
    at _next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:17:9)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
[2024-10-08 16:26:02] [[31merror[39m] TypeError: result.get is not a function
    at map (C:\My project\My project\back-end\src\services\/testService.js:114:25)
    at Array.map (<anonymous>)
    at _callee3$ (C:\My project\My project\back-end\src\services\/testService.js:112:37)
    at tryCatch (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:17)
    at _next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:17:9)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
[2024-10-08 16:28:43] [[31merror[39m] TypeError: Cannot read properties of undefined (reading 'count')
    at map (C:\My project\My project\back-end\src\services\/testService.js:120:74)
    at Array.map (<anonymous>)
    at _callee3$ (C:\My project\My project\back-end\src\services\/testService.js:117:37)
    at tryCatch (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:17)
    at _next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:17:9)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
[2024-10-08 16:31:01] [[31merror[39m] TypeError: Cannot read properties of undefined (reading 'exams')
    at map (C:\My project\My project\back-end\src\services\/testService.js:121:67)
    at Array.map (<anonymous>)
    at _callee3$ (C:\My project\My project\back-end\src\services\/testService.js:118:42)
    at tryCatch (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:17)
    at _next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:17:9)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
[2024-10-08 16:31:15] [[31merror[39m] TypeError: Cannot read properties of undefined (reading 'exams')
    at map (C:\My project\My project\back-end\src\services\/testService.js:122:67)
    at Array.map (<anonymous>)
    at _callee3$ (C:\My project\My project\back-end\src\services\/testService.js:119:42)
    at tryCatch (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:17)
    at _next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:17:9)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
[2024-10-08 16:31:46] [[31merror[39m] TypeError: Cannot read properties of undefined (reading 'count')
    at map (C:\My project\My project\back-end\src\services\/testService.js:122:67)
    at Array.map (<anonymous>)
    at _callee3$ (C:\My project\My project\back-end\src\services\/testService.js:119:42)
    at tryCatch (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:17)
    at _next (C:\My project\My project\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:17:9)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
[2024-10-09 16:35:11] [[31merror[39m] TypeError: Cannot read properties of undefined (reading 'create')
    at _callee$ (C:\My project\My project\Badminton\back-end\src\services\auth\/authService.js:16:29)
    at tryCatch (C:\My project\My project\Badminton\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (C:\My project\My project\Badminton\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (C:\My project\My project\Badminton\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (C:\My project\My project\Badminton\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:17)
    at _next (C:\My project\My project\Badminton\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:17:9)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
[2024-10-09 16:35:11] [[31merror[39m] TypeError: Cannot read properties of undefined (reading 'create')
    at _callee$ (C:\My project\My project\Badminton\back-end\src\services\auth\/authService.js:16:29)
    at tryCatch (C:\My project\My project\Badminton\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (C:\My project\My project\Badminton\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (C:\My project\My project\Badminton\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (C:\My project\My project\Badminton\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:17)
    at _next (C:\My project\My project\Badminton\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:17:9)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
[2024-10-09 16:35:40] [[31merror[39m] TypeError: Cannot read properties of undefined (reading 'create')
    at _callee$ (C:\My project\My project\Badminton\back-end\src\services\auth\/authService.js:16:29)
    at tryCatch (C:\My project\My project\Badminton\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (C:\My project\My project\Badminton\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (C:\My project\My project\Badminton\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (C:\My project\My project\Badminton\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:17)
    at _next (C:\My project\My project\Badminton\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:17:9)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
[2024-10-09 16:35:40] [[31merror[39m] TypeError: Cannot read properties of undefined (reading 'create')
    at _callee$ (C:\My project\My project\Badminton\back-end\src\services\auth\/authService.js:16:29)
    at tryCatch (C:\My project\My project\Badminton\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (C:\My project\My project\Badminton\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (C:\My project\My project\Badminton\back-end\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (C:\My project\My project\Badminton\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:17)
    at _next (C:\My project\My project\Badminton\back-end\node_modules\@babel\runtime\helpers\asyncToGenerator.js:17:9)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
[2024-10-10 09:07:19] [[31merror[39m] timeBooking.update is not a function
[2024-10-10 09:08:01] [[31merror[39m] Missing where attribute in the options parameter
[2024-10-10 10:16:18] [[31merror[39m] notNull Violation: BadmintonCourt.userId cannot be null
[2024-10-10 10:23:35] [[31merror[39m] WHERE parameter "courtNumberId" has invalid "undefined" value
[2024-10-10 10:23:57] [[31merror[39m] WHERE parameter "courtNumberId" has invalid "undefined" value
[2024-10-10 10:23:57] [[31merror[39m] WHERE parameter "courtNumberId" has invalid "undefined" value
[2024-10-10 10:25:19] [[31merror[39m] onRemoveParams is not defined
[2024-10-10 11:20:43] [[31merror[39m] User is not associated to Schedule!
[2024-10-10 11:25:33] [[31merror[39m] User is not associated to Schedule!
[2024-10-10 11:25:51] [[31merror[39m] UserBooking is associated to Schedule using an alias. You must use the 'as' keyword to specify the alias within your include statement.
[2024-10-10 11:26:40] [[31merror[39m] Cannot read properties of undefined (reading 'getTableName')
[2024-10-10 11:29:05] [[31merror[39m] User is not associated to Schedule!
[2024-10-10 11:32:28] [[31merror[39m] BadmintonCourt is not associated to UserBooking!
[2024-10-10 11:34:57] [[31merror[39m] CourtNumber is associated to BadmintonCourt using an alias. You must use the 'as' keyword to specify the alias within your include statement.
[2024-10-10 11:37:25] [[31merror[39m] Cannot read properties of undefined (reading 'getTableName')
[2024-10-10 11:37:38] [[31merror[39m] Cannot read properties of undefined (reading 'getTableName')
[2024-10-10 11:51:10] [[31merror[39m] Include unexpected. Element has to be either a Model, an Association or an object.
[2024-10-10 11:51:37] [[31merror[39m] Include unexpected. Element has to be either a Model, an Association or an object.
[2024-10-10 12:08:31] [[31merror[39m] Error: WHERE parameter "scheduleId" has invalid "undefined" value
    at MySQLQueryGenerator.whereItemQuery (C:\My project\My project\Badminton\back-end\node_modules\sequelize\src\dialects\abstract\query-generator.js:2445:13)
    at C:\My project\My project\Badminton\back-end\node_modules\sequelize\src\dialects\abstract\query-generator.js:2434:25
    at Array.forEach (<anonymous>)
    at MySQLQueryGenerator.whereItemsQuery (C:\My project\My project\Badminton\back-end\node_modules\sequelize\src\dialects\abstract\query-generator.js:2432:35)
    at MySQLQueryGenerator.whereQuery (C:\My project\My project\Badminton\back-end\node_modules\sequelize\src\dialects\abstract\query-generator.js:2405:24)
    at MySQLQueryGenerator.updateQuery (C:\My project\My project\Badminton\back-end\node_modules\sequelize\src\dialects\abstract\query-generator.js:515:116)
    at MySQLQueryInterface.bulkUpdate (C:\My project\My project\Badminton\back-end\node_modules\sequelize\src\dialects\abstract\query-interface.js:924:37)
    at Function.update (C:\My project\My project\Badminton\back-end\node_modules\sequelize\src\model.js:3352:54)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
[2024-10-10 12:08:44] [[31merror[39m] WHERE parameter "scheduleId" has invalid "undefined" value
[2024-10-10 12:10:12] [[31merror[39m] WHERE parameter "scheduleId" has invalid "undefined" value
[2024-10-10 12:10:31] [[31merror[39m] WHERE parameter "scheduleId" has invalid "undefined" value
[2024-10-10 13:04:52] [[31merror[39m] Cannot read properties of null (reading 'scheduleId')
[2024-10-10 13:05:33] [[31merror[39m] Cannot read properties of null (reading 'scheduleId')
[2024-10-10 13:05:51] [[31merror[39m] Cannot read properties of null (reading 'scheduleId')
[2024-10-10 13:06:06] [[31merror[39m] Cannot read properties of null (reading 'scheduleId')
[2024-10-11 14:22:03] [[31merror[39m] Cannot read properties of undefined (reading 'filename')
[2024-10-11 14:22:16] [[31merror[39m] Unknown column 'avatar' in 'field list'
[2024-10-11 14:22:16] [[31merror[39m] undefined
[2024-10-11 14:22:43] [[31merror[39m] Unknown column 'avatar' in 'field list'
[2024-10-11 14:22:43] [[31merror[39m] undefined
[2024-10-11 14:49:33] [[31merror[39m] Unknown column 'avatar' in 'field list'
[2024-10-11 14:49:33] [[31merror[39m] undefined
[2024-10-11 14:50:54] [[31merror[39m] Unknown column 'avatar' in 'field list'
[2024-10-11 14:50:54] [[31merror[39m] undefined
[2024-10-11 14:51:10] [[31merror[39m] Unknown column 'avatar' in 'field list'
[2024-10-11 14:51:10] [[31merror[39m] undefined
[2024-10-11 14:53:55] [[31merror[39m] data is not defined
[2024-10-11 15:30:08] [[31merror[39m] Cannot read properties of null (reading 'password')
[2024-10-16 11:08:38] [[31merror[39m] BaseResponse is not defined
[2024-10-16 17:38:26] [[31merror[39m] notNull Violation: BadmintonCourt.userId cannot be null
[2024-10-16 17:40:49] [[31merror[39m] notNull Violation: BadmintonCourt.userId cannot be null
[2024-10-16 17:42:21] [[31merror[39m] notNull Violation: BadmintonCourt.userId cannot be null
[2024-10-16 17:42:45] [[31merror[39m] notNull Violation: BadmintonCourt.userId cannot be null
[2024-10-16 17:43:35] [[31merror[39m] Cannot add or update a child row: a foreign key constraint fails (`db_badminton_web`.`badmintoncourts`, CONSTRAINT `badmintoncourts_ibfk_1` FOREIGN KEY (`userId`) REFERENCES `users` (`id`) ON DELETE CASCADE)
[2024-10-16 17:44:58] [[31merror[39m] Cannot add or update a child row: a foreign key constraint fails (`db_badminton_web`.`badmintoncourts`, CONSTRAINT `badmintoncourts_ibfk_1` FOREIGN KEY (`userId`) REFERENCES `users` (`id`) ON DELETE CASCADE)
[2024-10-16 17:46:18] [[31merror[39m] Cannot add or update a child row: a foreign key constraint fails (`db_badminton_web`.`badmintoncourts`, CONSTRAINT `badmintoncourts_ibfk_1` FOREIGN KEY (`userId`) REFERENCES `users` (`id`) ON DELETE CASCADE)
[2024-10-16 17:47:16] [[31merror[39m] Cannot add or update a child row: a foreign key constraint fails (`db_badminton_web`.`badmintoncourts`, CONSTRAINT `badmintoncourts_ibfk_1` FOREIGN KEY (`userId`) REFERENCES `users` (`id`) ON DELETE CASCADE)
[2024-10-16 17:49:12] [[31merror[39m] Cannot add or update a child row: a foreign key constraint fails (`db_badminton_web`.`badmintoncourts`, CONSTRAINT `badmintoncourts_ibfk_1` FOREIGN KEY (`userId`) REFERENCES `users` (`id`) ON DELETE CASCADE)
[2024-10-17 10:48:19] [[31merror[39m] TimeBooking is associated to Schedule using an alias. You've included an alias (timeBookings), but it does not match the alias(es) defined in your association (timeBooking).
[2024-10-17 10:54:34] [[31merror[39m] WHERE parameter "queryCourtNumber" has invalid "undefined" value
[2024-10-17 13:58:26] [[31merror[39m] district is not defined
[2024-10-17 13:59:56] [[31merror[39m] district is not defined
[2024-10-17 14:00:19] [[31merror[39m] district is not defined
[2024-10-17 14:24:49] [[31merror[39m] district is not defined
[2024-10-17 14:26:01] [[31merror[39m] district is not defined
[2024-10-17 14:26:38] [[31merror[39m] district is not defined
[2024-10-17 14:26:48] [[31merror[39m] district is not defined
[2024-10-17 17:46:07] [[31merror[39m] string violation: imageCourt cannot be an array or an object
[2024-10-17 17:46:13] [[31merror[39m] string violation: imageCourt cannot be an array or an object
[2024-10-17 17:47:13] [[31merror[39m] string violation: imageCourt cannot be an array or an object
[2024-10-17 17:49:16] [[31merror[39m] string violation: imageCourt cannot be an array or an object
[2024-10-17 17:49:35] [[31merror[39m] string violation: imageCourt cannot be an array or an object
[2024-10-17 17:52:13] [[31merror[39m] string violation: imageCourt cannot be an array or an object
[2024-10-17 17:53:51] [[31merror[39m] string violation: imageCourt cannot be an array or an object
[2024-10-17 18:02:36] [[31merror[39m] string violation: imageCourt cannot be an array or an object
[2024-10-21 09:16:09] [[31merror[39m] Cannot read properties of null (reading 'password')
[2024-10-21 09:30:04] [[31merror[39m] data is not defined
[2024-10-21 09:30:46] [[31merror[39m] data is not defined
[2024-10-21 09:33:23] [[31merror[39m] data is not defined
[2024-10-21 10:12:12] [[31merror[39m] Invalid attempt to destructure non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.
[2024-10-28 14:18:13] [[31merror[39m] FacilitiesRoom is associated to Facilities using an alias. You've included an alias (facilities), but it does not match the alias(es) defined in your association (facilitiesRooms).
[2024-10-28 14:18:13] [[31merror[39m] FacilitiesRoom is associated to Facilities using an alias. You've included an alias (facilities), but it does not match the alias(es) defined in your association (facilitiesRooms).
[2024-10-28 14:18:49] [[31merror[39m] Cannot read properties of undefined (reading 'map')
[2024-10-28 14:18:49] [[31merror[39m] Cannot read properties of undefined (reading 'map')
[2024-10-28 14:19:19] [[31merror[39m] Table 'db_badminton_web.facilities' doesn't exist
[2024-10-28 14:19:19] [[31merror[39m] Table 'db_badminton_web.facilities' doesn't exist
[2024-10-28 15:23:34] [[31merror[39m] facility.update is not a function
[2024-10-28 15:23:40] [[31merror[39m] facility.update is not a function
[2024-10-28 15:24:14] [[31merror[39m] facility.update is not a function
[2024-10-28 15:24:36] [[31merror[39m] Missing where attribute in the options parameter
